### ISSUE TITLE
What are units for definition of maximum allowed walking limit?

### ISSUE THREAD

**Issue by ekleiman22** [transnetlab/transit-routing#10]
In file **build_transfer_file.py** in function **extract_graph()** you  read a network using OSMnx package as:
`G = ox.graph_from_place(query, network_type='drive')`
According to description of this package length of edges of this network is measured in spatial units, not in time units. 
In function **initialize()** you request from an user to define maximum allowed walking limit in seconds and get  value WALKING_LIMIT.
Then in function **find_transfer_len** you find distance from each stop using graph G in function
`nx.single_source_dijkstra_path_length(G, source_info[1], cutoff=WALKING_LIMIT * 2, weight='length')`
And this is the place that **I don' t understand** because length of edges of this network is measured in spatial units but for cutoff you use time units. Can you explain this?

**Comment by Prateek1009** [comment]
Dear Ekleiman,

In my experience, the link lengths in OSM are typically measured in meters. I based my calculations on an assumed walking speed of 1 meter per second, making the cutoff (in seconds) directly correlated with length. Given the age of this issue, I'll be closing it now. If you have additional questions or need further clarification, please feel free to open a new issue. I assure you of a prompt response.
