### ISSUE TITLE
Development branch version works with anaheim only

### ISSUE THREAD

**Issue by ekleiman22** [transnetlab/transit-routing#9]
I downloaded transit-routing-development and tried to use. For Network name I wrote the name of my network, not anaheim. But then  I saw that directories for my network was not built and there was printed "Network: anaheim" and then there was error " No such file or directory: './Data/GTFS/mynetworkname"
Update: I see that in this version you save GTFS inside of DATA. So there is no issue.

**Comment by Prateek1009** [comment]
Dear Ekleiman, 

According to your update, the problem was resolved with the update. I will close this issue.
